// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fit_factor_model_log1p_exact_cpp_src
List fit_factor_model_log1p_exact_cpp_src(const std::vector<int>& sc_x, const std::vector<int>& sc_i, const std::vector<int>& sc_j, const std::vector<int>& sc_T_x, const std::vector<int>& sc_T_i, const std::vector<int>& sc_T_j, const arma::vec& s, arma::mat& U_T, arma::mat& V_T, const int n, const int p, const int max_iter, const double alpha, const double beta, const int num_ccd_iter, const std::vector<int>& update_indices);
RcppExport SEXP _passPCA_fit_factor_model_log1p_exact_cpp_src(SEXP sc_xSEXP, SEXP sc_iSEXP, SEXP sc_jSEXP, SEXP sc_T_xSEXP, SEXP sc_T_iSEXP, SEXP sc_T_jSEXP, SEXP sSEXP, SEXP U_TSEXP, SEXP V_TSEXP, SEXP nSEXP, SEXP pSEXP, SEXP max_iterSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP num_ccd_iterSEXP, SEXP update_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_x(sc_xSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_i(sc_iSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_j(sc_jSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_T_x(sc_T_xSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_T_i(sc_T_iSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_T_j(sc_T_jSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type U_T(U_TSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type V_T(V_TSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const int >::type num_ccd_iter(num_ccd_iterSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type update_indices(update_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_factor_model_log1p_exact_cpp_src(sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, s, U_T, V_T, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices));
    return rcpp_result_gen;
END_RCPP
}
// fit_factor_model_log1p_quad_approx_sparse_cpp_src
List fit_factor_model_log1p_quad_approx_sparse_cpp_src(const std::vector<int>& sc_x, const std::vector<int>& sc_i, const std::vector<int>& sc_j, const std::vector<int>& sc_T_x, const std::vector<int>& sc_T_i, const std::vector<int>& sc_T_j, const arma::vec& s, arma::mat& U_T, arma::mat& V_T, const double a1, const double a2, const int n, const int p, const int max_iter, const double alpha, const double beta, const int num_ccd_iter, const std::vector<int>& update_indices);
RcppExport SEXP _passPCA_fit_factor_model_log1p_quad_approx_sparse_cpp_src(SEXP sc_xSEXP, SEXP sc_iSEXP, SEXP sc_jSEXP, SEXP sc_T_xSEXP, SEXP sc_T_iSEXP, SEXP sc_T_jSEXP, SEXP sSEXP, SEXP U_TSEXP, SEXP V_TSEXP, SEXP a1SEXP, SEXP a2SEXP, SEXP nSEXP, SEXP pSEXP, SEXP max_iterSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP num_ccd_iterSEXP, SEXP update_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_x(sc_xSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_i(sc_iSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_j(sc_jSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_T_x(sc_T_xSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_T_i(sc_T_iSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type sc_T_j(sc_T_jSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type s(sSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type U_T(U_TSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type V_T(V_TSEXP);
    Rcpp::traits::input_parameter< const double >::type a1(a1SEXP);
    Rcpp::traits::input_parameter< const double >::type a2(a2SEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const int >::type num_ccd_iter(num_ccd_iterSEXP);
    Rcpp::traits::input_parameter< const std::vector<int>& >::type update_indices(update_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_factor_model_log1p_quad_approx_sparse_cpp_src(sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, s, U_T, V_T, a1, a2, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_passPCA_fit_factor_model_log1p_exact_cpp_src", (DL_FUNC) &_passPCA_fit_factor_model_log1p_exact_cpp_src, 16},
    {"_passPCA_fit_factor_model_log1p_quad_approx_sparse_cpp_src", (DL_FUNC) &_passPCA_fit_factor_model_log1p_quad_approx_sparse_cpp_src, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_passPCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
