// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// solve_pois_reg_log1p
arma::vec solve_pois_reg_log1p(const arma::mat X, const arma::vec y, const arma::uvec y_nz_idx, arma::vec b, const std::vector<int> update_indices, unsigned int num_iter, const double alpha, const double beta);
RcppExport SEXP _passPCA_solve_pois_reg_log1p(SEXP XSEXP, SEXP ySEXP, SEXP y_nz_idxSEXP, SEXP bSEXP, SEXP update_indicesSEXP, SEXP num_iterSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type y_nz_idx(y_nz_idxSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type update_indices(update_indicesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_pois_reg_log1p(X, y, y_nz_idx, b, update_indices, num_iter, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// solve_pois_reg_log1p_lin_approx
arma::vec solve_pois_reg_log1p_lin_approx(const arma::mat X_nz, const arma::vec y, const arma::vec X_0_cs_times_a, arma::vec b, const std::vector<int> update_indices, unsigned int num_iter, const double alpha, const double beta);
RcppExport SEXP _passPCA_solve_pois_reg_log1p_lin_approx(SEXP X_nzSEXP, SEXP ySEXP, SEXP X_0_cs_times_aSEXP, SEXP bSEXP, SEXP update_indicesSEXP, SEXP num_iterSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X_nz(X_nzSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type X_0_cs_times_a(X_0_cs_times_aSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type update_indices(update_indicesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_pois_reg_log1p_lin_approx(X_nz, y, X_0_cs_times_a, b, update_indices, num_iter, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// solve_pois_reg_log1p_quad_approx
arma::vec solve_pois_reg_log1p_quad_approx(const arma::mat X_nz, const arma::vec y, const arma::vec X_0_cs_times_a1, const arma::mat X_0_T_X_0, const double a2, arma::vec b, const std::vector<int> update_indices, unsigned int num_iter, const double alpha, const double beta);
RcppExport SEXP _passPCA_solve_pois_reg_log1p_quad_approx(SEXP X_nzSEXP, SEXP ySEXP, SEXP X_0_cs_times_a1SEXP, SEXP X_0_T_X_0SEXP, SEXP a2SEXP, SEXP bSEXP, SEXP update_indicesSEXP, SEXP num_iterSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X_nz(X_nzSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type X_0_cs_times_a1(X_0_cs_times_a1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X_0_T_X_0(X_0_T_X_0SEXP);
    Rcpp::traits::input_parameter< const double >::type a2(a2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type update_indices(update_indicesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_pois_reg_log1p_quad_approx(X_nz, y, X_0_cs_times_a1, X_0_T_X_0, a2, b, update_indices, num_iter, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// solve_pois_reg_log1p_quad_approx_full
arma::vec solve_pois_reg_log1p_quad_approx_full(const arma::mat X_nz, const arma::vec y, const arma::vec X_cs_times_a1, const arma::mat X_T_X, const double a2, arma::vec b, const std::vector<int> update_indices, unsigned int num_iter, const double alpha, const double beta);
RcppExport SEXP _passPCA_solve_pois_reg_log1p_quad_approx_full(SEXP X_nzSEXP, SEXP ySEXP, SEXP X_cs_times_a1SEXP, SEXP X_T_XSEXP, SEXP a2SEXP, SEXP bSEXP, SEXP update_indicesSEXP, SEXP num_iterSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X_nz(X_nzSEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec >::type X_cs_times_a1(X_cs_times_a1SEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X_T_X(X_T_XSEXP);
    Rcpp::traits::input_parameter< const double >::type a2(a2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type update_indices(update_indicesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type num_iter(num_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(solve_pois_reg_log1p_quad_approx_full(X_nz, y, X_cs_times_a1, X_T_X, a2, b, update_indices, num_iter, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// get_num_repeats
std::vector<int> get_num_repeats(const std::vector<int> idx, const int p, const int total_idx);
RcppExport SEXP _passPCA_get_num_repeats(SEXP idxSEXP, SEXP pSEXP, SEXP total_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<int> >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const int >::type total_idx(total_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(get_num_repeats(idx, p, total_idx));
    return rcpp_result_gen;
END_RCPP
}
// create_vals_list
List create_vals_list(const int num_vectors, const std::vector<int> vector_sizes, const std::vector<int> values);
RcppExport SEXP _passPCA_create_vals_list(SEXP num_vectorsSEXP, SEXP vector_sizesSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type num_vectors(num_vectorsSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type vector_sizes(vector_sizesSEXP);
    Rcpp::traits::input_parameter< const std::vector<int> >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(create_vals_list(num_vectors, vector_sizes, values));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_passPCA_solve_pois_reg_log1p", (DL_FUNC) &_passPCA_solve_pois_reg_log1p, 8},
    {"_passPCA_solve_pois_reg_log1p_lin_approx", (DL_FUNC) &_passPCA_solve_pois_reg_log1p_lin_approx, 8},
    {"_passPCA_solve_pois_reg_log1p_quad_approx", (DL_FUNC) &_passPCA_solve_pois_reg_log1p_quad_approx, 10},
    {"_passPCA_solve_pois_reg_log1p_quad_approx_full", (DL_FUNC) &_passPCA_solve_pois_reg_log1p_quad_approx_full, 10},
    {"_passPCA_get_num_repeats", (DL_FUNC) &_passPCA_get_num_repeats, 3},
    {"_passPCA_create_vals_list", (DL_FUNC) &_passPCA_create_vals_list, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_passPCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
