# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_factor_model_log1p_exact_cpp_src <- function(sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, s, U_T, V_T, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices) {
    .Call(`_passPCA_fit_factor_model_log1p_exact_cpp_src`, sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, s, U_T, V_T, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices)
}

fit_factor_model_log1p_lin_approx_sparse_cpp_src <- function(sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, s, U_T, V_T, a, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices) {
    .Call(`_passPCA_fit_factor_model_log1p_lin_approx_sparse_cpp_src`, sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, s, U_T, V_T, a, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices)
}

fit_factor_model_log1p_quad_approx_full_cpp_src <- function(sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, U_T, V_T, a1, a2, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices) {
    .Call(`_passPCA_fit_factor_model_log1p_quad_approx_full_cpp_src`, sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, U_T, V_T, a1, a2, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices)
}

fit_factor_model_log1p_quad_approx_sparse_cpp_src <- function(sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, s, c, sum_Y, sum_s, U_T, V_T, a0, a1, a2, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices, fit_c) {
    .Call(`_passPCA_fit_factor_model_log1p_quad_approx_sparse_cpp_src`, sc_x, sc_i, sc_j, sc_T_x, sc_T_i, sc_T_j, s, c, sum_Y, sum_s, U_T, V_T, a0, a1, a2, n, p, max_iter, alpha, beta, num_ccd_iter, update_indices, fit_c)
}

